### ISSUE TITLE
thDisable does not work as expected

### ISSUE THREAD

**Issue by JohnWu-Pro** [thymol/thymol.js#11]
Found in version: 2.0.0-beta2

The following code
```javascript
var thDebug = true;
var thDisable = [ "include", "substituteby", "replace" ];
```
will result in an alert as follows
```
cannot disable unknown attribute "include"
```

**Comment by jjbenson** [comment]
Hi,

  Many thanks for taking the time to report this. You have found another serious regression defect!

  In a re-work of the code that handles disabling, I carelessly forgot that the following attributes needed special treatment:

  "include", "substituteby", "replace" and also "fragment" and "remove".

  There was another defect concealed by the one that you found (that caused the alert), and that makes it even better that you reported it!

  I have coded fixes for these cases and pushed them to the head. You can grab a snapshot copy with the fix here: https://github.com/thymol/thymol.js/tree/2.x-master.

Thanks again!

  Jim

**Comment by jjbenson** [comment]
Hi JohnWu-Pro,

In the absence of any further comment I am assuming that this issue can now be closed. Please re-open if you find any problems.

Kind Regards,

    Jim
