### ISSUE TITLE
Feature Request: Make i18n message substitution optional

### ISSUE THREAD

**Issue by JohnWu-Pro** [thymol/thymol.js#12]
As Thymol is designed to be an emulation of Thymeleaf templating system, it may make sense in some scenario to disable i18n message substitution and keep the corresponding message place holders.

For example
```html
<title th:text="#{edit.pageTitle}">Online Shopping Cart - Enter Quantity</title>
```
results in
```html
<title">Online Shopping Cart - Enter Quantity</title>
```

and 

```html
<input name="command" value="Review" th:attr="value=#{edit.button.review}" />
```
results in
```html
<input name="command" value="Review" />
```

I made it works in a kinda hacking way, as follows
```javascript
thymol.ready(function () {
    thymol.configurePreExecution( function() {
        // Disables fetching i18n property files
        thymol.getMessage = function() {};

        // Keeps i18n placeholders without substitution
        // TODO: Enhance to handle all scenarios
        thymol.originSubsParam = thymol.substituteParam;
        thymol.substituteParam = function(argValue, mode, element) {
            if(mode===4) {
                return element.value ? element.value : element.innerHTML; 
            } else {
                return thymol.originSubsParam(argValue, mode, element);
            }
        };
    });
});
```

It would be better to add a control parameter to achieve the same result.

**Comment by jjbenson** [comment]
Hi JohnWu-Pro,

  I like your idea very much and will look into implementing it when I get a chance.

  Your hack is very cool though - I admire it's uncompromising approach ;^)

  Seriously though, it's great that users like you are getting to grips with the code and really using the features.

  Kind Regards,

    Jim

**Comment by jjbenson** [comment]
Hi JohnWu-Pro,

I've pushed a new version that tries to address this issue, although this is also some kind of hack..

You can now set:

  thDisableMessages = true;

To achieve the desired effect.

You can change the default value of this control (e.g. for an entire project) by setting the value of thDefaultDisableMessages in Thymol.js. The normal default value is "false".

You can find a build with the latest version at:

  https://github.com/thymol/thymol.js/tree/2.x-master

Please re-open this issue if you find any problems. I'm not completely convinced that all the corner cases have been covered.

Kind Regards,

    Jim
