### ISSUE TITLE
Add an option to define the suffix for the thymeleaf template

### ISSUE THREAD

**Issue by LucDepauw** [thymol/thymol.js#13]
In thymeleaf it's possible to have the resolver add a suffix ex. '.html' to the template name.
Since I don't want to do this, my template/fragment is referenced in thymeleaf like this 'fragment/common.html'
Thymol doesn't find the template if referenced like this th:include='fragment/common.html::headerFragment'  only this works
th:include='fragment/common::headerFragment'
But then my thymeleaf resolver failes...
Is there a way to define a suffix for the template in the thymol configuration ?

**Comment by jjbenson** [comment]
Hi Luc,

I've pushed a new version that addresses this issue.

You can now set:

  thTemplateSuffix = "";

To achieve the desired effect.

You can change the default value of the template suffix (e.g. for an entire project) by setting the value of thDefaultTemplateSuffix in Thymol.js. The normal default value is (of course!) ".html".

You can find a build with the latest version at:

  https://github.com/thymol/thymol.js/tree/2.x-master

Please re-open this issue if you find any problems.

Kind Regards,

    Jim
