### ISSUE TITLE
.unload() has been removed in jQuery 3

### ISSUE THREAD

**Issue by Jaizkibel** [thymol/thymol.js#17]
there is one usage of unload() in thymol.js:

`$(window).unload(function() {...})`

should by replaced by

`$(window).on('unload', function() {...})`

**Comment by jjbenson** [comment]
This is now delivered in thymol-2.0.1-pre.4.

**Comment by mychalvlcek** [comment]
@jjbenson and where can i get mentioned version of thymo.js build (not node build)

**Comment by jjbenson** [comment]
@mychalvlcek You can find the latest build output at https://github.com/thymol/thymol.js/tree/2.x-master
