### ISSUE TITLE
th:inline scripts outputs single quotes for strings

### ISSUE THREAD

**Issue by panganibanpj** [thymol/thymol.js#22]
```
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/thymol/2.0.0/thymol.min.js" data-jquery-src="" data-thymol-load="page-data.js"></script>
    <!-- page-data.js
          thymol.applicationContext.createVariable("obj", { "foo": "bar" } );
    -->
  </head>
  <body>
    <script th:inline="javascript" type="application/ld+json">
      /*[[ ${obj} ]]*/
    </script>
  </body>
</html>
```

When I do this, the innerHTML of the inline script reads:
```
{ 'foo': 'bar' }
```
which is invalid JSON because of single quotes. IIRC thymeleaf itself was doing this before version 2

**Comment by jjbenson** [comment]
I think Thymeleaf was doing this before version 3, and as Thymol is supposed to be implementing Thymeleaf 2 syntax it make sense to leave the default quoting regime as it is currently.
However, I've added a new control to allow you to choose the quote character to use when writing text when th:inline="javascript" is in force. The control is "thymol.inlineQuote", it's value defaults to the single quote character.

**Comment by panganibanpj** [comment]
This is awesome! Thank you! Is this on the latest release? Feel free to close this

**Comment by jjbenson** [comment]
The inlineQuote control is implemented in the current trunk (as of 24 March 2017). You  can find the build outputs containing this [here](https://github.com/thymol/thymol.js/tree/2.x-master).
