### ISSUE TITLE
Make it available through CDN

### ISSUE THREAD

**Issue by dtrunk90** [thymol/thymol.js#6]
osscdn.com would be great for example

**Comment by jjbenson** [comment]
Thymol is now available via the excellent jsdelivr network! You can now access Thymol files at lightning speed using http://cdn.jsdelivr.net/thymol/latest/thymol.min.js.

For more information see https://github.com/jsdelivr/jsdelivr.

The corresponding osscdn address is: http://oss.maxcdn.com/thymol/latest/thymol.min.js.

**Comment by dtrunk90** [comment]
Great, thanks a lot.
